location_flag_ids = {
    1: "Japes Lanky Mad Maze Maul",
    2: "Japes Tiny Splish-Splash Salvage",
    # 3: "Japes Donkey Baboon Blast",
    4: "Japes Donkey In front of Diddy's Cage",
    5: "Japes Donkey In Diddy's Cage",
    6: "Kong Unlocked: Diddy",
    # 8: "Japes Tiny Stump",
    # 9: "Japes Tiny Beehive",
    # 10: "Japes Lanky Painting Room Zingers",
    11: "Japes Lanky Speedy Swing Sortie",
    # 12: "Japes Chunky Underground",
    18: "Japes Diddy Caged GB",
    19: "Japes Lanky Caged GB",
    20: "Japes Donkey Caged GB",
    21: "Japes Tiny Caged GB",
    22: "Japes Chunky Caged GB",
    23: "Japes Diddy Mountain Top (W5)",
    # 24: "Japes Diddy Minecart",
    # 25: "Japes Chunky Boulder",
    # 26: "Key 1",
    28: "Japes Chunky Minecart Mayhem",
    31: "Japes Diddy Cave",
    # 49: "Aztec Chunky Vases",
    # 51: "Aztec Donkey Free Llama Blast",
    # 52: "Aztec Chunky Giant Caged Barrel",
    # 54: "Aztec Diddy Ram Gongs",
    # 56: "Aztec Diddy 5 Door Temple",
    # 57: "Aztec Donkey 5 Door Temple",
    # 58: "Aztec Tiny 5 Door Temple",
    # 59: "Aztec Chunky 5 Door Temple",
    # 60: "Aztec Lanky 5 Door Temple",
    62: "Aztec Donkey W5",
    # 63: "Aztec Diddy Vulture Race",
    64: "Aztec Chunky Rotating Room",
    65: "Aztec Tiny Tiny Temple",
    66: "Kong Unlocked: Tiny",
    67: "Aztec Diddy Tiny's Cage",
    # 68: "Aztec Lanky Vulture Shooting",
    70: "Kong Unlocked: Lanky",
    # 71: "Aztec Tiny Llama Temple Lava Pedestals",
    # 72: "Aztec Lanky Matching Game",
    73: "Aztec Lanky Teetering Turtle Trouble",
    # 74: "Key 2",
    # 75: "Aztec Tiny Beetle Race",
    77: "Aztec Donkey Free Lanky",
    # 112: "Factory Donkey Power Hut",
    # 113: "Factory Diddy Production Spring",
    # 114: "Factory Chunky Production Timer",
    # 115: "Factory Lanky Production Handstand",
    # 116: "Factory Tiny Production Twirl",
    117: "Kong Unlocked: Chunky",
    118: "Factory Lanky Free Chunky",
    # 121: "Factory Chunky Dark Room",
    # 122: "Factory Donkey Number Game",
    # 123: "Factory Tiny Mini by Arcade",
    # 124: "Factory Tiny Dartboard",
    # 125: "Factory Lanky Piano Game",
    # 126: "Factory Diddy Charge Enemies",
    # 127: "Factory Chunky Toy Monster",
    # 128: "Factory Donkey Crusher Room",
    # 130: "Factory Donkey DK Arcade Round 1",
    132: "Nintendo Coin",
    134: "Factory Diddy Beaver Bother",
    # 135: "Factory Diddy Block Tower",
    136: "Factory Chunky Stash Snatch",
    137: "Factory Lanky Batty Barrel Bandit",
    # 138: "Key 3",
    # 139: "Factory Tiny Car Race",
    # 154: "Galleon Chunky Cannon Game",
    # 157: "Galleon Donkey Lighthouse",
    163: "Galleon Diddy W4",
    164: "Galleon Lanky Gold Tower",
    # 165: "Galleon Donkey Seal Race",
    # 166: "Galleon Chunky Seasick",
    # 167: "Galleon Diddy Mechfish",
    # 168: "Key 4",
    # 182: "Galleon Chunky Chest",
    # 183: "Galleon Lanky 2 Door Ship",
    # 184: "Galleon Tiny 2 Door Ship",
    # 191: "Galleon Tiny Mermaid Reward",
    # 192: "Galleon Lanky Enguarde Chest",
    # 193: "Galleon Donkey Free the Seal",
    # 197: "Galleon Chunky 5 Door Ship",
    # 198: "Galleon Diddy 5 Door Ship",
    # 199: "Galleon Lanky 5 Door Ship",
    # 200: "Galleon Donkey 5 Door Ship",
    # 201: "Galleon Tiny 5 Door Ship",
    202: "Galleon Tiny Submarine",
    # 204: "Galleon Diddy Top of Lighthouse",
    205: "Forest Tiny Anthill",
    # 209: "Forest Tiny Top of the Beanstalk",
    211: "Forest Diddy Top of Mushroom",
    # 214: "Forest Diddy Winch Cage",
    # 215: "Forest Chunky Minecart",
    216: "Forest Diddy Barn",
    # 217: "Forest Lanky Attic Shooting",
    # 219: "Forest Donkey Mill Levers",
    # 221: "Forest Chunky Keg Crushing",
    # 224: "Forest Lanky Colored Mushroom Slam",
    # 225: "Forest Chunky Face Puzzle",
    # 226: "Forest Lanky Zinger Bounce",
    227: "Forest Tiny Speedy Swing Sortie",
    # 228: "Forest Donkey Mushroom Cannons",
    235: "Forest Donkey Minecart Mayhem",
    # 236: "Key 5",
    # 247: "Forest Tiny Spider Boss",
    # 249: "Forest Lanky Rabbit Race",
    # 250: "Forest Diddy Owl Race",
    # 253: "Forest Chunky Apple Rescue",
    # 254: "Forest Donkey Baboon Blast",
    # 259: "Caves Lanky Beetle Race",
    # 260: "Caves Tiny 5 Door Cabin",
    # 261: "Caves Donkey 5 Door Cabin",
    # 262: "Caves Diddy 5 Door Cabin Lower",
    # 263: "Caves Chunky 5 Door Cabin",
    # 264: "Caves Lanky Sprint Cabin",
    268: "Caves Chunky Entrance Ice Wall",
    270: "Caves Chunky Chunky Igloo",
    # 271: "Caves Lanky Ice Castle Slam Challenge",
    # 274: "Caves Diddy 5 Door Igloo",
    # 275: "Caves Donkey 5 Door Igloo",
    # 276: "Caves Donkey Rotating Cabin",
    # 278: "Caves Chunky 5 Door Igloo",
    # 279: "Caves Tiny 5 Door Igloo",
    # 281: "Caves Lanky 5 Door Igloo",
    # 292: "Key 6",
    # 293: "Caves Diddy 5 Door Cabin Upper",
    294: "Caves Diddy Mad Maze Maul",
    295: "Caves Tiny W3",
    # 297: "Caves Tiny Monkeyport Igloo",
    # 298: "Caves Donkey Baboon Blast",
    301: "Isles Tiny Rareware GB",
    # 305: "Castle Diddy Ballroom",
    # 306: "Castle Lanky Tower",
    308: "Castle Lanky Orangstand GB",
    309: "Castle Tiny Goo Hands",
    # 310: "Castle Diddy Crypt",
    # 311: "Castle Chunky Crypt",
    # 313: "Castle Donkey Library",
    # 314: "Castle Chunky Museum",
    315: "Castle Tiny Dungeon",
    # 316: "Castle Lanky Dungeon",
    # 317: "Key 7",
    # 318: "Castle Donkey Minecart",
    # 319: "Castle Chunky Tree Sniping Barrel",
    # 320: "Castle Donkey Tree Sniping",
    # 322: "Castle Chunky Shed",
    # 323: "Castle Lanky Greenhouse",
    # 325: "Castle Tiny Car Race",
    326: "Castle Donkey Face Puzzle",
    350: "Castle Diddy Big Bug Bash",
    # 351: "Castle Tiny Trash Can",
    353: "Castle Diddy Chain Room",
    379: "Rareware Coin",
    # 380: "Key 8",
    # 381: "Isles Japes Lobby Entrance Item",
    385: "Kong Unlocked: Donkey",
    # 398: "Isles Lanky Japes Instrument",
    402: "Isles Tiny Big Bug Bash",
    # 403: "Isles Tiny Galleon Lobby Swim",
    # 404: "Isles Donkey Bongos Pad",
    406: "Isles Chunky Helm Lobby Kremling Kosh",
    # 410: "Isles Diddy Guitar Pad",
    # 411: "Isles Donkey Caves Lava",
    415: "Isles Lanky Searchlight seek",
    416: "Isles Diddy Batty Barrel Bandit",
    # 419: "Isles Donkey Coconut Cage",
    # 420: "Isles Tiny Feather Cage",
    # 421: "Isles Lanky Grape Cage",
    # 422: "Isles Chunky Pineapple Cage",
    # 423: "Isles Diddy Peanut Cage",
    # 424: "Isles Chunky Triangle Pad",
    # 425: "Isles Tiny Saxophone Pad",
    428: "Isles Diddy Peril Path Panic!",
    # 429: "Isles Lanky Sprint Cage",
    # 431: "Isles Chunky Pound the X",
    444: "Key 1 Turned",
    445: "Key 2 Turned",
    446: "Key 3 Turned",
    447: "Key 4 Turned",
    448: "Key 5 Turned",
    449: "Key 6 Turned",
    450: "Key 7 Turned",
    451: "Key 8 Turned",
    469: "Japes Blueprint - Donkey",
    470: "Japes Blueprint - Diddy",
    471: "Japes Blueprint - Lanky",
    472: "Japes Blueprint - Tiny",
    473: "Japes Blueprint - Chunky",
    474: "Aztec Blueprint - Donkey",
    475: "Aztec Blueprint - Diddy",
    476: "Aztec Blueprint - Lanky",
    477: "Aztec Blueprint - Tiny",
    478: "Aztec Blueprint - Chunky",
    479: "Factory Blueprint - Donkey",
    480: "Factory Blueprint - Diddy",
    481: "Factory Blueprint - Lanky",
    482: "Factory Blueprint - Tiny",
    483: "Factory Blueprint - Chunky",
    484: "Galleon Blueprint - Donkey",
    485: "Galleon Blueprint - Diddy",
    486: "Galleon Blueprint - Lanky",
    487: "Galleon Blueprint - Tiny",
    488: "Galleon Blueprint - Chunky",
    489: "Forest Blueprint - Donkey",
    490: "Forest Blueprint - Diddy",
    491: "Forest Blueprint - Lanky",
    492: "Forest Blueprint - Tiny",
    493: "Forest Blueprint - Chunky",
    494: "Caves Blueprint - Donkey",
    495: "Caves Blueprint - Diddy",
    496: "Caves Blueprint - Lanky",
    497: "Caves Blueprint - Tiny",
    498: "Caves Blueprint - Chunky",
    499: "Castle Blueprint - Donkey",
    500: "Castle Blueprint - Diddy",
    501: "Castle Blueprint - Lanky",
    502: "Castle Blueprint - Tiny",
    503: "Castle Blueprint - Chunky",
    504: "Isles Blueprint - Donkey",
    505: "Isles Blueprint - Diddy",
    506: "Isles Blueprint - Lanky",
    507: "Isles Blueprint - Tiny",
    508: "Isles Blueprint - Chunky",
    # 509: "Turn In Jungle Japes Donkey Blueprint",
    # 510: "Turn In Jungle Japes Diddy Blueprint",
    # 511: "Turn In Jungle Japes Lanky Blueprint",
    # 512: "Turn In Jungle Japes Tiny Blueprint",
    # 513: "Turn In Jungle Japes Chunky Blueprint",
    # 514: "Turn In Angry Aztec Donkey Blueprint",
    # 515: "Turn In Angry Aztec Diddy Blueprint",
    # 516: "Turn In Angry Aztec Lanky Blueprint",
    # 517: "Turn In Angry Aztec Tiny Blueprint",
    # 518: "Turn In Angry Aztec Chunky Blueprint",
    # 519: "Turn In Frantic Factory Donkey Blueprint",
    # 520: "Turn In Frantic Factory Diddy Blueprint",
    # 521: "Turn In Frantic Factory Lanky Blueprint",
    # 522: "Turn In Frantic Factory Tiny Blueprint",
    # 523: "Turn In Frantic Factory Chunky Blueprint",
    # 524: "Turn In Gloomy Galleon Donkey Blueprint",
    # 525: "Turn In Gloomy Galleon Diddy Blueprint",
    # 526: "Turn In Gloomy Galleon Lanky Blueprint",
    # 527: "Turn In Gloomy Galleon Tiny Blueprint",
    # 528: "Turn In Gloomy Galleon Chunky Blueprint",
    # 529: "Turn In Forest Forest Donkey Blueprint",
    # 530: "Turn In Forest Forest Diddy Blueprint",
    # 531: "Turn In Forest Forest Lanky Blueprint",
    # 532: "Turn In Forest Forest Tiny Blueprint",
    # 533: "Turn In Forest Forest Chunky Blueprint",
    # 534: "Turn In Crystal Caves Donkey Blueprint",
    # 535: "Turn In Crystal Caves Diddy Blueprint",
    # 536: "Turn In Crystal Caves Lanky Blueprint",
    # 537: "Turn In Crystal Caves Tiny Blueprint",
    # 538: "Turn In Crystal Caves Chunky Blueprint",
    # 539: "Turn In Creepy Castle Donkey Blueprint",
    # 540: "Turn In Creepy Castle Diddy Blueprint",
    # 541: "Turn In Creepy Castle Lanky Blueprint",
    # 542: "Turn In Creepy Castle Tiny Blueprint",
    # 543: "Turn In Creepy Castle Chunky Blueprint",
    # 544: "Turn In Donkey Isles Donkey Blueprint",
    # 545: "Turn In Donkey Isles Diddy Blueprint",
    # 546: "Turn In Donkey Isles Lanky Blueprint",
    # 547: "Turn In Donkey Isles Tiny Blueprint",
    # 548: "Turn In Donkey Isles Chunky Blueprint",
    # 549: "Japes Donkey Medal",
    # 550: "Japes Diddy Medal",
    # 551: "Japes Lanky Medal",
    # 552: "Japes Tiny Medal",
    # 553: "Japes Chunky Medal",
    # 554: "Aztec Donkey Medal",
    # 555: "Aztec Diddy Medal",
    # 556: "Aztec Lanky Medal",
    # 557: "Aztec Tiny Medal",
    # 558: "Aztec Chunky Medal",
    # 559: "Factory Donkey Medal",
    # 560: "Factory Diddy Medal",
    # 561: "Factory Lanky Medal",
    # 562: "Factory Tiny Medal",
    # 563: "Factory Chunky Medal",
    # 564: "Galleon Donkey Medal",
    # 565: "Galleon Diddy Medal",
    # 566: "Galleon Lanky Medal",
    # 567: "Galleon Tiny Medal",
    # 568: "Galleon Chunky Medal",
    # 569: "Forest Donkey Medal ",
    # 570: "Forest Diddy Medal: ",
    # 571: "Forest Lanky Medal",
    # 572: "Forest Tiny Medal",
    # 573: "Forest Chunky Medal",
    # 574: "Caves Donkey Medal",
    # 575: "Caves Diddy Medal",
    # 576: "Caves Lanky Medal",
    # 577: "Caves Tiny Medal",
    # 578: "Caves Chunky Medal",
    # 579: "Castle Donkey Medal",
    # 580: "Castle Diddy Medal",
    # 581: "Castle Lanky Medal",
    # 582: "Castle Tiny Medal",
    # 583: "Castle Chunky Medal",
    # 584: "Helm Donkey Medal",
    # 585: "Helm Chunky Medal",
    # 586: "Helm Lanky Medal",
    # 587: "Helm Tiny Medal",
    # 588: "Helm Diddy Medal",
    # 589: "Japes Fairy (Rambi Door Pool)",
    # 590: "Japes Fairy (Painting Room)",
    # 591: "Factory Fairy (Near Funky's)",
    # 592: "Galleon Fairy (In Punch Chest)",
    # 593: "Isles Fairy (Factory Lobby)",
    # 594: "Isles Fairy (Forest Lobby)",
    # 595: "Forest Fairy (Dark Rafters)",
    # 596: "Forest Fairy (Thornvine Barn)",
    # 597: "Caves Fairy (Tiny Igloo)",
    # 598: "Helm Fairy (Key 8 Room (1))",
    # 599: "Helm Fairy (Key 8 Room (2))",
    # 600: "Aztec Fairy (Llama Temple)",
    # 601: "Aztec Fairy (Tiny 5-Door Temple)",
    # 602: "Factory Fairy (Number Game)",
    # 603: "Galleon Fairy (In Tiny's 5-Door Ship)",
    # 604: "Castle Fairy (Near Car Race)",
    # 605: "Castle Fairy (Tree Sniper Room)",
    # 606: "Isles Fairy (Small Island)",
    # 607: "Isles Fairy (Upper Krem Isles)",
    # 608: "Caves Fairy (Diddy Candles Cabin)",
    # 609: "Japes Battle Arena (Near Funky)",
    # 610: "Aztec Battle Arena (Tiny Temple: Vulture Room)",
    # 611: "Factory Battle Arena (Under R and D Grate)",
    # 612: "Galleon Battle Arena (Under Cranky)",
    # 613: "Forest Battle Arena (Giant Mushroom High Ladder Platform)",
    # 614: "Isles Battle Arena 2 (Fungi Lobby: Gorilla Gone Box)",
    # 615: "Isles Battle Arena 1 (Snide's Room: Under Rock)",
    # 616: "Caves Battle Arena (Rotating Room: Left Portion)",
    # 617: "Castle Battle Arena (Greenhouse: Center)",
    # 618: "Helm Battle Arena (Top of Blast-o-Matic)",
    # 621: "Japes Dirt: Painting Hill",
    # 646: "Aztec Dirt: Chunky Temple",
    # 661: "Factory Dirt: Dark Room",
    # 676: "Isles Dirt: Cabin Isle",
    # 677: "Isles Dirt: Under Caves Lobby",
    # 678: "Isles Dirt: Aztec Roof",
    # 685: "Aztec Dirt: Oasis",
    # 687: "Forest Dirt: Mills Grass",
    # 690: "Forest Dirt: Beanstalk",
    # 694: "Galleon Dirt: Lighthouse",
    # 703: "Caves Dirt: Giant Kosha",
    # 713: "Castle Dirt: Top Floor",
    # 718: "Isles Dirt: Back of Prison",
    # 735: "Isles Dirt: Training Grounds Rear Tunnel",
    # 736: "Isles Dirt: Banana Hoard",
    # 739: "Isles Dirt: Castle Lobby",
}
